In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from utils import print_column_with_nan, clean_value, get_columns_with_nan

In [2]:
DATASET_PATH = '../data/acute_coronary_syndrome_db.xlsx'
df = pd.read_excel(DATASET_PATH, sheet_name=0, usecols=range(0, 74))

In [3]:
# Asumptions
NUMERICAL_FEATURES = ['PESO Kg', 'ALTURA cm', 'TROPONINA MAX', 'CREAT', 'GLUCEMIA INGR', 'GB', 'TAS INGRESO', 'FC INGRESO', 'NUMERO VASOS']
NUMERICAL_CONTINOUS = NUMERICAL_FEATURES
CATEGORY_FEATURES = ['SEX0', 'HTA', 'DBT', 'DLP', 'TABAQ', 'ANTEC IAM / Angina inestable', 'ANTEC BY PASS', 'ANTEC ATC', 'ANTEC ACE', 'ANTEC INS RENAL', 'ACV TIA PREV', 'EPOC', 'CLAUD ITTE', 'BB PREV', ' IECA/AT2  PREV', 'B CA PREV', 'AAS PREV', 'HIPOGLUCEMIANTES', 'DIURETICOS', 'INSULINA', 'ECG INFRA ST', 'ECG SUPRA ST', 'ECG INV T', 'BRI', 'BRD', 'ECG MCP', 'ECG FA', 'tropst', 'TnT Ultrasensible', 'Elevacion troponina T', 'KILLIP Ingreso', 'AAS', 'BB', 'IECA', 'AT2', 'Clopi - prasu - tica', 'HEP sc o iv', 'IIb IIIa', 'B CA', 'ESTATINAS', 'HIPOGLUC METFORM', 'HIPOGL SULFAN', 'HIPOGL GLITAZ', 'INSULINA', 'INS + HIPOGL', 'INOTROPICOS', 'FUNCION VENTRICULAR IZQ', 'DIAGNOSTICO', 'PRUEBA FUNC.', 'PRUEBA FUNC DE ALTO RIESGO', 'CCG', 'TRONCO', 'ATC PRIMARIA', 'ATC INTRAHOSP', 'TROMBOL', 'CRM', 'IAM HOSP(SI INTERNO POR ANGINA) O REIAM', 'APIAM', 'Peor KILLIP', 'ANGINA REFRACT o RECURR', ' ACV/TIA', 'SANGRADO MAYOR*', 'I RENAL AGUDA']

TARGET = "MUERTE HOSP"

In [4]:
print_column_with_nan(df)

EDAD NaNs: 0 - 0.0%
SEX0 NaNs: 0 - 0.0%
HTA NaNs: 0 - 0.0%
DBT NaNs: 0 - 0.0%
DLP NaNs: 0 - 0.0%
TABAQ NaNs: 0 - 0.0%
ANTEC IAM / Angina inestable NaNs: 0 - 0.0%
ANTEC BY PASS NaNs: 0 - 0.0%
ANTEC ATC NaNs: 0 - 0.0%
ANTEC ACE NaNs: 0 - 0.0%
ANTEC INS RENAL NaNs: 0 - 0.0%
ACV TIA PREV NaNs: 0 - 0.0%
EPOC NaNs: 0 - 0.0%
CLAUD ITTE NaNs: 0 - 0.0%
BB PREV NaNs: 0 - 0.0%
 IECA/AT2  PREV NaNs: 0 - 0.0%
B CA PREV NaNs: 0 - 0.0%
AAS PREV NaNs: 0 - 0.0%
HIPOGLUCEMIANTES NaNs: 0 - 0.0%
DIURETICOS NaNs: 0 - 0.0%
INSULINA NaNs: 0 - 0.0%
PESO Kg NaNs: 93 - 5.115511551155116%
ALTURA cm NaNs: 119 - 6.5456545654565454%
ECG INFRA ST NaNs: 0 - 0.0%
ECG SUPRA ST NaNs: 0 - 0.0%
ECG INV T NaNs: 0 - 0.0%
BRI NaNs: 1 - 0.05500550055005501%
BRD NaNs: 0 - 0.0%
ECG MCP NaNs: 0 - 0.0%
ECG FA NaNs: 1 - 0.05500550055005501%
tropst NaNs: 2 - 0.11001100110011001%
TnT Ultrasensible NaNs: 0 - 0.0%
TROPONINA MAX NaNs: 4 - 0.22002200220022003%
Elevacion troponina T NaNs: 0 - 0.0%
CREAT NaNs: 8 - 0.44004400440044006%
GLUCEMIA INGR NaNs: 37 - 2.0352035203520353%
GB NaNs: 33 - 1.8151815181518152%
TAS INGRESO NaNs: 12 - 0.6600660066006601%
FC INGRESO NaNs: 11 - 0.605060506050605%
KILLIP Ingreso NaNs: 0 - 0.0%
AAS NaNs: 0 - 0.0%
BB NaNs: 1 - 0.05500550055005501%
IECA NaNs: 0 - 0.0%
AT2 NaNs: 1 - 0.05500550055005501%
Clopi - prasu - tica NaNs: 0 - 0.0%
HEP sc o iv NaNs: 0 - 0.0%
IIb IIIa NaNs: 0 - 0.0%
B CA NaNs: 1 - 0.05500550055005501%
ESTATINAS NaNs: 0 - 0.0%
HIPOGLUC METFORM NaNs: 1 - 0.05500550055005501%
HIPOGL SULFAN NaNs: 0 - 0.0%
HIPOGL GLITAZ NaNs: 4 - 0.22002200220022003%
INSULINA.1 NaNs: 1 - 0.05500550055005501%
INS + HIPOGL NaNs: 1 - 0.05500550055005501%
INOTROPICOS NaNs: 2 - 0.11001100110011001%
FUNCION VENTRICULAR IZQ NaNs: 3 - 0.16501650165016502%
DIAGNOSTICO NaNs: 1 - 0.05500550055005501%
PRUEBA FUNC. NaNs: 0 - 0.0%
PRUEBA FUNC DE ALTO RIESGO NaNs: 1 - 0.05500550055005501%
CCG NaNs: 0 - 0.0%
TRONCO NaNs: 1 - 0.05500550055005501%
NUMERO VASOS NaNs: 2 - 0.11001100110011001%
ATC PRIMARIA NaNs: 0 - 0.0%
ATC INTRAHOSP NaNs: 0 - 0.0%
TROMBOL NaNs: 1 - 0.05500550055005501%
CRM NaNs: 3 - 0.16501650165016502%
MUERTE HOSP NaNs: 0 - 0.0%
IAM HOSP(SI INTERNO POR ANGINA) O REIAM NaNs: 3 - 0.16501650165016502%
APIAM NaNs: 3 - 0.16501650165016502%
Peor KILLIP NaNs: 0 - 0.0%
ANGINA REFRACT o RECURR NaNs: 3 - 0.16501650165016502%
 ACV/TIA NaNs: 4 - 0.22002200220022003%
SANGRADO MAYOR* NaNs: 4 - 0.22002200220022003%
I RENAL AGUDA NaNs: 2 - 0.11001100110011001%

Procedemos a ver cuales son las columnas tipo `object` y hacemos una limpieza de los datos erroneos, nulos o vacios.

In [4]:
# Obtenemos las columnas de tipo object
object_columns = df.select_dtypes(include=['object']).columns

df[object_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1818 entries, 0 to 1817
Data columns (total 9 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ALTURA cm                                1699 non-null   object
 1   TROPONINA MAX                            1814 non-null   object
 2   CREAT                                    1810 non-null   object
 3   GLUCEMIA INGR                            1781 non-null   object
 4   GB                                       1785 non-null   object
 5   BB                                       1817 non-null   object
 6   INOTROPICOS                              1816 non-null   object
 7   FUNCION VENTRICULAR IZQ                  1815 non-null   object
 8   IAM HOSP(SI INTERNO POR ANGINA) O REIAM  1815 non-null   object
dtypes: object(9)
memory usage: 128.0+ KB

Vemos que tipo de datos unicos tenemos en cada columna

In [5]:
for column in object_columns:
  print(f"{column}: {df[column].unique()}")

ALTURA cm: [155 165 172 162 175 160 178 182 168 157 169 180 170 167 173 179 187 159
 156 171 183 158 176 150 177 186 174 163 161 185 166 164 154 55 181 82 135
 193 147 nan 153 184 190 194 ' ' 142 189 151 149 152 148 199 200 144 197
 146 191 196 188 108 192 195 73 70 80 75 130]
TROPONINA MAX: [0.2 0.05 0 0.08 4.3 1.93 0.1 1.35 0.19 0.09 0.246 0.25 1.5 0.052 1.7 0.01
 2.09 1.1 0.075 0.15 1.9 0.049 0.126 3.87 0.7 2.75 0.3 2.3 1.47 0.428
 0.046 11 0.63 2 0.13 1.2 0.011 0.058 0.027 10 0.11 7 9 0.5 0.9 0.047 0.87
 0.55 0.65 0.52 3.1 5 7.3 0.012 0.8 1 1.8 12.6 1.6 0.037 '0.086' '0.04'
 '0.019' 1.19 0.018 6.7 2.4 6.9 0.18 0.26 0.33 1.45 '0.68' '1.9' '0.01'
 0.015 0.6 12 13 '0.58' '0.3' '0.29' 1.3 0.48 '0.12' 16 0.026 0.32 0.07
 '0.5' 2.33 '0.011' 0.06 0.43 '<0,01' 5.2 0.45 0.16 0.12 5.8 0.4 0.03
 0.022 1.37 0.22 '0.88' 0.67 0.04 0.14 0.02 '2.45' 0.157 0.147 0.036 0.57
 2.69 4.5 3.79 0.75 0.854 3.2 0.038 0.165 0.29 0.134 0.685 '6.09' 0.043
 0.016 '5.4' 0.23 6.5 0.42 0.39 0.647 0.481 0.072 5.76 8.5 0.66 0.033 6.82
 3 6 2975 14 34 28 20 24 3342 321 2125 3101 161 57 6081 nan 4481 10516 22
 918 8 21 15 996 447 1554 2040 50 101 5685 1939 1473 9620 68 49 5957 40
 102 3917 54 23 320 746 150 430 992 1595 171 1676 7047 1646 61 32 280 35
 1381 18 3897 1392 19 4 1650 173 780 1848 130 99 17 333 535 290 1904 41 37
 1259 765 4347 72 18661 858 244 274 2615 2473 317 803 '<3' 70 155 1013 51
 148 5071 1266 209 5003 1067 3298 3081 142 46 126 582 10569 1594 1760 983
 67 10633 63 335 2600 76 495 273 289 226 356 1427 10000 755 956 617 786
 304 195 1119 200 3701 107 5700 486 700 26 62 47 59 685 703 56 30 114 45
 149 2862 391 80 340 3827 207 271 796 502 352 6855 473 348 2175 10903 31
 27 119 100 1105 554 83 66 52 1366 360 43 481 224 1134 611 118 1507 86
 14341 29 1031 3609 3253 9675 988 64 672 298 630 347 98 197 48 13601 8255
 159 196 900 151 77 609 108 659 33 1578 125 489 500 232 110 328 9916 1130
 94 583 1414 182 205 88 471 2266 25 2625 222 186 2543 147 6668 131 136
 8323 2200 297 3938 115 3640 121 1569 467 726 1922 277 163 2969 285 4250
 127 466 74 1416 1053 2358 240 138 548 206 65 407 81 1022 3062 626 516
 10428 933 300 594 2063 543 90 818 44 624 113 6375 176 189 84 16635 58 512
 308 693 255 157 3900 262 877 2643 399 111 768 73 329 479 55 727 181 584
 1222 3857 36 427 179 744 1171 145 686 1868 773 92 168 1047 228 42 166 250
 1050 2454 1058 143 253 1398 14240 294 4556 10702 287 6075 194 4033 7249
 797 2584 560 6283 621 128 905 156 2104 29374 648 120 270 9976 6727 245
 233 7930 1746 678 10634 2441 15471 15578 14110 338 225 135 784 2084 613
 231 2067 606 716 12909 7430 141 238 1280 293 71 2163 800 75 4065 14722
 139 491 265 967 20309 847 339 124 6198 898 1537 105 814 237 514 203 443
 715 409 2393 378 5332 9529 89 679 722 633 798 3501 880 210 692 103 3191
 191 3518 4960 14760 2922 18346 1220 254 4450 1097 470 9312 2693 2491 2797
 53 243 21388 4900 7368 941 214 393 435 175 3550 2707 1032 4499 8546 2950
 4807 39 1234 5576 4833 24883 241 5418 5438 12149 523 3043 2239 480 6131
 1530 279 3758 1000 260 78 1898 87 249 7743 1182 4872 7619 4267 284 591
 14228 4279 259 3339 11870 79 6394 40000 160 4130 11438 6228 3212 1147
 1614 4097 6323 2375 538 14500 5792 5600 6515 643 1500 759 710 452 428
 1680 307 463 116 91 1476 1198 4385 461 1682 1678 4388 1411 201 492 212
 9582 242 133 1126 104 355 1258 1577 499 2094 507 4922 1901 154 152 2244
 358 403 2022 7443 219 3223 82 5400 1094 1321 3151 1360 282 134 1294 137
 375 351 96 230 379 '-' 448 593 874 236 1315 751 1962 5858 627 268 446 106
 247 7976 331 19200 631 1084 2014 946 129 1219 7787 1781 5331 386 1788 299
 167 7257 6362 1756 555 1205 1593 2133 1028 522 332 4280 31184 5212 4858
 368 4268 870 93 85 1993 984 2667 19835 707 3890 426 2091 991 1726 9175
 323 202 3309 1103 3447 192 397 170 2416 1210 218 112 1803 1059 622 9306
 11786 344 1598 221 966 482 3194 394 16947 4354 132 363 1946 3670]
CREAT: [0.58 1.06 0.83 0.85 0.88 0.52 0.87 1.14 1.37 1.03 1.12 0.8 0.79 1.22 0.74
 1.02 0.72 1.23 0.7 1.2 1.04 1.05 0.56 0.9 0.53 0.5 0.97 0.95 0.94 0.98
 0.92 1.09 1.53 0.6 1.6 0.93 0.81 1.07 1.4 0.86 0.77 0.55 2.2 0.99 1 1.24
 1.1 1.19 1.3 0.76 0.78 0.84 1.35 0.96 1.68 4 1.13 1.7 1.25 1.27 1.11 0.69
 0.68 1.67 1.5 1.17 1.86 1.26 0.75 0.89 0.67 0.65 1.29 0.66 1.36 1.48 1.18
 1.99 1.16 0.71 0.73 0.13 1.15 0.63 1.01 nan 0.82 1.32 1.31 0.62 1.76 1.56
 1.95 0.61 0.38 1.08 0.64 1.47 14 1.62 1.54 2.03 3.32 0.91 7.63 1.57 1.46
 2.71 1.75 1.64 3.17 3.69 1.9 2.8 1.33 1.63 1.52 1.88 1.28 0.42 1.59 0.54
 2.28 0.57 1.41 1.42 1.84 ' ' 1.73 0.06 1.58 1.49 1.87 1.38 1.81 2 0.59
 1.65 1.39 1.98 2.6 0.45 1.74 1.45 1.34 1.85 0.51 2.76 4.97 8.24 1.77
 '1,03' 1.51 1.66 2.33 5.95 2.14 2.3 2.01 1.21 2.09 2.17 1.71 2.26 6.04
 7.1 1.79 0.43 7.84 3.8 0.12 0.4 1.55 1.43 1.72 2.05 1.94 0.47 4.69 7.32
 4.11 2.74 1.78 3.61 2.7 1.69 2.1 1.44]
GLUCEMIA INGR: [160 131 98 106 110 146 97 96 137 107 171 350 121 94 126 109 142 184 99
 147 103 154 112 92 114 116 113 118 252 136 100 206 140 102 166 82 87 125
 104 224 93 120 108 360 127 179 69 150 266 122 176 141 325 95 91 134 123
 129 153 130 88 124 192 209 90 86 175 85 115 221 79 201 173 101 117 203
 143 428 161 261 240 105 530 165 78 60 119 168 222 138 331 182 74 nan 77
 232 185 135 ' ' 164 145 174 132 253 133 89 156 144 235 167 247 158 111
 401 75 159 128 189 61 244 177 225 152 199 352 76 157 263 172 183 149 223
 139 155 271 83 169 204 193 219 170 334 665 84 335 81 340 197 163 229 313
 322 186 310 191 323 208 227 278 200 80 256 196 148 250 251 497 220 65 217
 190 404 180 151 375 265 303 215 258 309 214 260 188 338 70 308 162 68 194
 472 187 275 343 295 318 237 72 212 213 336 255 285 448 205 239 230 408
 300 218 202 337 178 324 272 198 248 279 282 391 63 679 276 315]
GB: [8920 10340 6780 5830 14990 7500 10800 7340 11100 11040 8410 7280 5540
 14830 10410 22360 8380 5470 6640 7970 9970 6010 7840 6240 7640 7670 13540
 5740 10200 6850 13150 5770 6200 9700 7400 5790 4200 7130 6520 4490 9790
 6390 9030 6650 9450 5940 8340 6920 11680 7080 9150 6170 9190 8760 10470
 9510 8940 5390 4000 8430 8860 13410 7110 6450 10150 29870 6280 9170 5150
 9650 12360 7845 6725 6260 5634 6570 10610 7880 9320 14560 7380 6990 9240
 11310 5750 4510 11000 12220 5440 7570 4030 6070 11810 2940 7010 9210 5630
 7910 8400 11210 5490 7720 6610 6700 10770 ' ' 7370 5130 8460 12920 9640
 6080 9280 19100 10310 7850 11370 3630 7740 6899 7630 5520 4512 9480 5200
 10110 9520 7260 9812 9120 5100 12660 10860 6630 11050 10240 5689 5960
 10880 7780 7060 12700 4040 17070 7823 11030 11090 8540 13640 7250 5690
 6100 6720 9370 5860 12900 8040 7490 4660 9800 7930 8570 6420 8790 6860
 5280 6000 8130 16410 8270 16580 12290 9890 5900 nan 71900
 datetime.datetime(2024, 3, 13, 0, 0) datetime.datetime(2024, 3, 16, 0, 0)
 datetime.datetime(2024, 8, 7, 0, 0) 9920 7160
 datetime.datetime(2024, 12, 7, 0, 0) 6730
 datetime.datetime(2024, 5, 19, 0, 0) datetime.datetime(2024, 4, 11, 0, 0)
 9380 datetime.datetime(2024, 9, 8, 0, 0) 15800 5710 8280 8140 5190 6340
 7800 11700 6020 7600 6790 4430 7200 21140 8110 6140 9950 8220 12180 8030
 8000 7820 9110 8820 9160 6710 9670 9570 4980 5890 14040 2760 9310 6580
 9040 12830 5450 4460 7020 6560 7470 5820 9560 11500 5670 8420 3810 8680
 14750 8750 6690 8500 4610 10720 12860 6480 9420 5800 8560 4860 6320 9830
 6620 5870 5340 6490 9500 7330 14420 9400 7180 7480 11520 4140 6500 7580
 18860 10100 5300 6050 1090 11790 7240 20320 9990 6820 9080 4150 8510 6550
 17850 6970 4740 12800 11760 13280 10950 5590 11660 7220 7660 4240 5880
 12810 8580 12760 9180 6460 9750 8550 8080 9880 13290 5950 8060 7290 9900
 6950 6120 7170 5840 6540 10440 5310 5780 8310 19400 12600 11850 8020
 19440 7440 10490 10300 8950 5420 9820 13190 6800 10270 8666 4390 7300
 5760 12880 6290 12640 2360 10080 14380 8990 4930 9330 9200 10570 6400
 10370 14490 12840 6900 7150 9760 8300 11540 8740 12570 15910 10620 7450
 13489 4960 9590 22700 7090 7190 4060 11940 13120 5850 14980 5220 5320
 6370 9100 11780 7040 17730 11720 4870 8210 6890 16620 19940 7620 14860
 6350 9840 5020 11390 6410 5040 11080 7960 17090 10550 13340 8010 5720
 9710 11610 17960 4640 9540 4770 8090 8720 13100 9070 10910 7710 4850 8700
 7830 5410 15210 3660 8200 6870 8070 7750 6130 5980 9870 16180 5080 13300
 7900 9780 3980 6220 6190 7550 5700 12090 14000 4220 4810 8830 27480 6430
 11510 5000 8730 7430 6750 7390 19000 30240 7270 11140 12590 8970 10700
 13770 4570 7000 10870 8290 10960 9410 6740 9930 7940 1106 8881 16660 6770
 7360 5210 4630 8630 15380 7590 11010 8640 5545 11120 7268 4130 9140 11200
 15500 8330 8660 6840 11550 1080 10650 8520 8910 5530 14360 4290 13590
 10740 3520 2312 7460 33045 2190 7650 14650 11560 6600 10970 16140 11890
 6210 8390 5230 2800 6960 4560 5430 10050 6230 8470 8800 29190 10580 13810
 12140 13260 7680 8250 7210 8780 12260 6180 4590 19070 8150 16520 9050
 14200 7890 13110 11480 16600 5480 7760 18100 13360 5500 10000 9470 5330
 9770 9810 2050 15110 9260 6360 8840 11470 18540 11570 10010 6590 6980
 8490 7860 5650 7690 5090 4050 7980 12560 7950 6250 5460 18520 8370 6940
 7140 13140 12240 10380 14470 15520 8530 5970 8160 10640 10400 8930 10040
 14210 13680 10670 12510 5160 10420 13370 8880 15700 16230 7870 4400 10220
 13670 16090 6670 7050 11770 9430 4270 8050 5640 7120 9610 9350 6470 11020
 3780 16590 5290 8260 9220 6440 17390 3890 11070 11690 9690 5610 10830
 12110 12400 7310 11190 7770 11900 9530 13080 11830 11410 9620 7100 9630
 12780 9960 9270 6150 6830 5510 7540 15770 15040 6012 12420 10840 12620
 13790 15390 5140 12540 7560 5600 8600 10500 10160 6110 9230 8180 8240
 8480 8650 10320 13500 3870 15650 10070 16360 9000 7070 6330 8610 9720
 12310 18720 10920 14020 14580 14620 5250 4720 12870 12520 15590 6660
 10680 10980 14640 13030 1050 21190 12790 7790 9860 22180 25710 8230 20090
 4340 11330 11640 23580 12230 11240 26660 10430 4800 5730 10001 14110
 14530 8100 11800 11280 5570 12000 10450 13200 15000 4100 20000 10600
 13780 9020 10120 12070 11490 16810 4350 11400 5661 8850 4970 8690 25000
 10780 11130 9090 11110 6040 13620 11350 28050 9130 10460 8590 11970 20970
 4900 4920 8190 6060 10280 9730 13700 5110 10190 6090 15570 12990 6760
 9290 3680 7700 6910 9390 1541 10060 5117 12270 19960 11220 11060 4600
 15920 9360 11820 11620 9250 13650 15080 10730 8320 3960 7410 3700 15290
 15320 14250 10170 6030 4170 12550 12610 14070 11710 19510 7420 19970
 12190 16800 8900 8710 5180 13350 8620 15020 12670 11360 18880 13240 8350
 11840 13270 datetime.datetime(2024, 6, 8, 0, 0) 9600 14140 5920
 datetime.datetime(2024, 4, 5, 0, 0) 9440 8670 3440 8890 3560 15750
 datetime.datetime(1943, 10, 21, 0, 0) datetime.datetime(1921, 5, 9, 0, 0)
 datetime.datetime(2094, 12, 7, 0, 0) datetime.datetime(1953, 5, 21, 0, 0)
 datetime.datetime(1924, 5, 13, 0, 0) 11450
 datetime.datetime(2024, 3, 12, 0, 0) datetime.datetime(2024, 6, 5, 0, 0)
 datetime.datetime(2024, 1, 7, 0, 0) datetime.datetime(2024, 6, 6, 0, 0)
 9550 15600]
BB: [1 0 ' ' nan]
INOTROPICOS: [0 1 ' ' nan]
FUNCION VENTRICULAR IZQ: [1 2 3 nan ' ' 4]
IAM HOSP(SI INTERNO POR ANGINA) O REIAM: [0 1 '1 (periprocedimiento)' '1 perioperatorio' nan]

Observamos tipos de lo mas variados: numeros, strings, dates, nan.

In [6]:
# Aplicamos la función solo a las columnas definidas en object_columns
df[object_columns] = df[object_columns].applymap(clean_value)

C:\Users\andre\AppData\Local\Temp\ipykernel_32020\1794062239.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[object_columns] = df[object_columns].applymap(clean_value)

In [7]:
for column in object_columns:
  print(f"{column}: {df[column].unique()}")

ALTURA cm: [155. 165. 172. 162. 175. 160. 178. 182. 168. 157. 169. 180. 170. 167.
 173. 179. 187. 159. 156. 171. 183. 158. 176. 150. 177. 186. 174. 163.
 161. 185. 166. 164. 154.  55. 181.  82. 135. 193. 147.  nan 153. 184.
 190. 194. 142. 189. 151. 149. 152. 148. 199. 200. 144. 197. 146. 191.
 196. 188. 108. 192. 195.  73.  70.  80.  75. 130.]
TROPONINA MAX: [0.2 0.05 0 0.08 4.3 1.93 0.1 1.35 0.19 0.09 0.246 0.25 1.5 0.052 1.7 0.01
 2.09 1.1 0.075 0.15 1.9 0.049 0.126 3.87 0.7 2.75 0.3 2.3 1.47 0.428
 0.046 11 0.63 2 0.13 1.2 0.011 0.058 0.027 10 0.11 7 9 0.5 0.9 0.047 0.87
 0.55 0.65 0.52 3.1 5 7.3 0.012 0.8 1 1.8 12.6 1.6 0.037 '0.086' '0.04'
 '0.019' 1.19 0.018 6.7 2.4 6.9 0.18 0.26 0.33 1.45 '0.68' '1.9' '0.01'
 0.015 0.6 12 13 '0.58' '0.3' '0.29' 1.3 0.48 '0.12' 16 0.026 0.32 0.07
 '0.5' 2.33 '0.011' 0.06 0.43 '0,01' 5.2 0.45 0.16 0.12 5.8 0.4 0.03 0.022
 1.37 0.22 '0.88' 0.67 0.04 0.14 0.02 '2.45' 0.157 0.147 0.036 0.57 2.69
 4.5 3.79 0.75 0.854 3.2 0.038 0.165 0.29 0.134 0.685 '6.09' 0.043 0.016
 '5.4' 0.23 6.5 0.42 0.39 0.647 0.481 0.072 5.76 8.5 0.66 0.033 6.82 3 6
 2975 14 34 28 20 24 3342 321 2125 3101 161 57 6081 nan 4481 10516 22 918
 8 21 15 996 447 1554 2040 50 101 5685 1939 1473 9620 68 49 5957 40 102
 3917 54 23 320 746 150 430 992 1595 171 1676 7047 1646 61 32 280 35 1381
 18 3897 1392 19 4 1650 173 780 1848 130 99 17 333 535 290 1904 41 37 1259
 765 4347 72 18661 858 244 274 2615 2473 317 803 '3' 70 155 1013 51 148
 5071 1266 209 5003 1067 3298 3081 142 46 126 582 10569 1594 1760 983 67
 10633 63 335 2600 76 495 273 289 226 356 1427 10000 755 956 617 786 304
 195 1119 200 3701 107 5700 486 700 26 62 47 59 685 703 56 30 114 45 149
 2862 391 80 340 3827 207 271 796 502 352 6855 473 348 2175 10903 31 27
 119 100 1105 554 83 66 52 1366 360 43 481 224 1134 611 118 1507 86 14341
 29 1031 3609 3253 9675 988 64 672 298 630 347 98 197 48 13601 8255 159
 196 900 151 77 609 108 659 33 1578 125 489 500 232 110 328 9916 1130 94
 583 1414 182 205 88 471 2266 25 2625 222 186 2543 147 6668 131 136 8323
 2200 297 3938 115 3640 121 1569 467 726 1922 277 163 2969 285 4250 127
 466 74 1416 1053 2358 240 138 548 206 65 407 81 1022 3062 626 516 10428
 933 300 594 2063 543 90 818 44 624 113 6375 176 189 84 16635 58 512 308
 693 255 157 3900 262 877 2643 399 111 768 73 329 479 55 727 181 584 1222
 3857 36 427 179 744 1171 145 686 1868 773 92 168 1047 228 42 166 250 1050
 2454 1058 143 253 1398 14240 294 4556 10702 287 6075 194 4033 7249 797
 2584 560 6283 621 128 905 156 2104 29374 648 120 270 9976 6727 245 233
 7930 1746 678 10634 2441 15471 15578 14110 338 225 135 784 2084 613 231
 2067 606 716 12909 7430 141 238 1280 293 71 2163 800 75 4065 14722 139
 491 265 967 20309 847 339 124 6198 898 1537 105 814 237 514 203 443 715
 409 2393 378 5332 9529 89 679 722 633 798 3501 880 210 692 103 3191 191
 3518 4960 14760 2922 18346 1220 254 4450 1097 470 9312 2693 2491 2797 53
 243 21388 4900 7368 941 214 393 435 175 3550 2707 1032 4499 8546 2950
 4807 39 1234 5576 4833 24883 241 5418 5438 12149 523 3043 2239 480 6131
 1530 279 3758 1000 260 78 1898 87 249 7743 1182 4872 7619 4267 284 591
 14228 4279 259 3339 11870 79 6394 40000 160 4130 11438 6228 3212 1147
 1614 4097 6323 2375 538 14500 5792 5600 6515 643 1500 759 710 452 428
 1680 307 463 116 91 1476 1198 4385 461 1682 1678 4388 1411 201 492 212
 9582 242 133 1126 104 355 1258 1577 499 2094 507 4922 1901 154 152 2244
 358 403 2022 7443 219 3223 82 5400 1094 1321 3151 1360 282 134 1294 137
 375 351 96 230 379 '' 448 593 874 236 1315 751 1962 5858 627 268 446 106
 247 7976 331 19200 631 1084 2014 946 129 1219 7787 1781 5331 386 1788 299
 167 7257 6362 1756 555 1205 1593 2133 1028 522 332 4280 31184 5212 4858
 368 4268 870 93 85 1993 984 2667 19835 707 3890 426 2091 991 1726 9175
 323 202 3309 1103 3447 192 397 170 2416 1210 218 112 1803 1059 622 9306
 11786 344 1598 221 966 482 3194 394 16947 4354 132 363 1946 3670]
CREAT: [0.58 1.06 0.83 0.85 0.88 0.52 0.87 1.14 1.37 1.03 1.12 0.8 0.79 1.22 0.74
 1.02 0.72 1.23 0.7 1.2 1.04 1.05 0.56 0.9 0.53 0.5 0.97 0.95 0.94 0.98
 0.92 1.09 1.53 0.6 1.6 0.93 0.81 1.07 1.4 0.86 0.77 0.55 2.2 0.99 1 1.24
 1.1 1.19 1.3 0.76 0.78 0.84 1.35 0.96 1.68 4 1.13 1.7 1.25 1.27 1.11 0.69
 0.68 1.67 1.5 1.17 1.86 1.26 0.75 0.89 0.67 0.65 1.29 0.66 1.36 1.48 1.18
 1.99 1.16 0.71 0.73 0.13 1.15 0.63 1.01 nan 0.82 1.32 1.31 0.62 1.76 1.56
 1.95 0.61 0.38 1.08 0.64 1.47 14 1.62 1.54 2.03 3.32 0.91 7.63 1.57 1.46
 2.71 1.75 1.64 3.17 3.69 1.9 2.8 1.33 1.63 1.52 1.88 1.28 0.42 1.59 0.54
 2.28 0.57 1.41 1.42 1.84 1.73 0.06 1.58 1.49 1.87 1.38 1.81 2 0.59 1.65
 1.39 1.98 2.6 0.45 1.74 1.45 1.34 1.85 0.51 2.76 4.97 8.24 1.77 '1,03'
 1.51 1.66 2.33 5.95 2.14 2.3 2.01 1.21 2.09 2.17 1.71 2.26 6.04 7.1 1.79
 0.43 7.84 3.8 0.12 0.4 1.55 1.43 1.72 2.05 1.94 0.47 4.69 7.32 4.11 2.74
 1.78 3.61 2.7 1.69 2.1 1.44]
GLUCEMIA INGR: [160. 131.  98. 106. 110. 146.  97.  96. 137. 107. 171. 350. 121.  94.
 126. 109. 142. 184.  99. 147. 103. 154. 112.  92. 114. 116. 113. 118.
 252. 136. 100. 206. 140. 102. 166.  82.  87. 125. 104. 224.  93. 120.
 108. 360. 127. 179.  69. 150. 266. 122. 176. 141. 325.  95.  91. 134.
 123. 129. 153. 130.  88. 124. 192. 209.  90.  86. 175.  85. 115. 221.
  79. 201. 173. 101. 117. 203. 143. 428. 161. 261. 240. 105. 530. 165.
  78.  60. 119. 168. 222. 138. 331. 182.  74.  nan  77. 232. 185. 135.
 164. 145. 174. 132. 253. 133.  89. 156. 144. 235. 167. 247. 158. 111.
 401.  75. 159. 128. 189.  61. 244. 177. 225. 152. 199. 352.  76. 157.
 263. 172. 183. 149. 223. 139. 155. 271.  83. 169. 204. 193. 219. 170.
 334. 665.  84. 335.  81. 340. 197. 163. 229. 313. 322. 186. 310. 191.
 323. 208. 227. 278. 200.  80. 256. 196. 148. 250. 251. 497. 220.  65.
 217. 190. 404. 180. 151. 375. 265. 303. 215. 258. 309. 214. 260. 188.
 338.  70. 308. 162.  68. 194. 472. 187. 275. 343. 295. 318. 237.  72.
 212. 213. 336. 255. 285. 448. 205. 239. 230. 408. 300. 218. 202. 337.
 178. 324. 272. 198. 248. 279. 282. 391.  63. 679. 276. 315.]
GB: [ 8920. 10340.  6780.  5830. 14990.  7500. 10800.  7340. 11100. 11040.
  8410.  7280.  5540. 14830. 10410. 22360.  8380.  5470.  6640.  7970.
  9970.  6010.  7840.  6240.  7640.  7670. 13540.  5740. 10200.  6850.
 13150.  5770.  6200.  9700.  7400.  5790.  4200.  7130.  6520.  4490.
  9790.  6390.  9030.  6650.  9450.  5940.  8340.  6920. 11680.  7080.
  9150.  6170.  9190.  8760. 10470.  9510.  8940.  5390.  4000.  8430.
  8860. 13410.  7110.  6450. 10150. 29870.  6280.  9170.  5150.  9650.
 12360.  7845.  6725.  6260.  5634.  6570. 10610.  7880.  9320. 14560.
  7380.  6990.  9240. 11310.  5750.  4510. 11000. 12220.  5440.  7570.
  4030.  6070. 11810.  2940.  7010.  9210.  5630.  7910.  8400. 11210.
  5490.  7720.  6610.  6700. 10770.    nan  7370.  5130.  8460. 12920.
  9640.  6080.  9280. 19100. 10310.  7850. 11370.  3630.  7740.  6899.
  7630.  5520.  4512.  9480.  5200. 10110.  9520.  7260.  9812.  9120.
  5100. 12660. 10860.  6630. 11050. 10240.  5689.  5960. 10880.  7780.
  7060. 12700.  4040. 17070.  7823. 11030. 11090.  8540. 13640.  7250.
  5690.  6100.  6720.  9370.  5860. 12900.  8040.  7490.  4660.  9800.
  7930.  8570.  6420.  8790.  6860.  5280.  6000.  8130. 16410.  8270.
 16580. 12290.  9890.  5900. 71900.  9920.  7160.  6730.  9380. 15800.
  5710.  8280.  8140.  5190.  6340.  7800. 11700.  6020.  7600.  6790.
  4430.  7200. 21140.  8110.  6140.  9950.  8220. 12180.  8030.  8000.
  7820.  9110.  8820.  9160.  6710.  9670.  9570.  4980.  5890. 14040.
  2760.  9310.  6580.  9040. 12830.  5450.  4460.  7020.  6560.  7470.
  5820.  9560. 11500.  5670.  8420.  3810.  8680. 14750.  8750.  6690.
  8500.  4610. 10720. 12860.  6480.  9420.  5800.  8560.  4860.  6320.
  9830.  6620.  5870.  5340.  6490.  9500.  7330. 14420.  9400.  7180.
  7480. 11520.  4140.  6500.  7580. 18860. 10100.  5300.  6050.  1090.
 11790.  7240. 20320.  9990.  6820.  9080.  4150.  8510.  6550. 17850.
  6970.  4740. 12800. 11760. 13280. 10950.  5590. 11660.  7220.  7660.
  4240.  5880. 12810.  8580. 12760.  9180.  6460.  9750.  8550.  8080.
  9880. 13290.  5950.  8060.  7290.  9900.  6950.  6120.  7170.  5840.
  6540. 10440.  5310.  5780.  8310. 19400. 12600. 11850.  8020. 19440.
  7440. 10490. 10300.  8950.  5420.  9820. 13190.  6800. 10270.  8666.
  4390.  7300.  5760. 12880.  6290. 12640.  2360. 10080. 14380.  8990.
  4930.  9330.  9200. 10570.  6400. 10370. 14490. 12840.  6900.  7150.
  9760.  8300. 11540.  8740. 12570. 15910. 10620.  7450. 13489.  4960.
  9590. 22700.  7090.  7190.  4060. 11940. 13120.  5850. 14980.  5220.
  5320.  6370.  9100. 11780.  7040. 17730. 11720.  4870.  8210.  6890.
 16620. 19940.  7620. 14860.  6350.  9840.  5020. 11390.  6410.  5040.
 11080.  7960. 17090. 10550. 13340.  8010.  5720.  9710. 11610. 17960.
  4640.  9540.  4770.  8090.  8720. 13100.  9070. 10910.  7710.  4850.
  8700.  7830.  5410. 15210.  3660.  8200.  6870.  8070.  7750.  6130.
  5980.  9870. 16180.  5080. 13300.  7900.  9780.  3980.  6220.  6190.
  7550.  5700. 12090. 14000.  4220.  4810.  8830. 27480.  6430. 11510.
  5000.  8730.  7430.  6750.  7390. 19000. 30240.  7270. 11140. 12590.
  8970. 10700. 13770.  4570.  7000. 10870.  8290. 10960.  9410.  6740.
  9930.  7940.  1106.  8881. 16660.  6770.  7360.  5210.  4630.  8630.
 15380.  7590. 11010.  8640.  5545. 11120.  7268.  4130.  9140. 11200.
 15500.  8330.  8660.  6840. 11550.  1080. 10650.  8520.  8910.  5530.
 14360.  4290. 13590. 10740.  3520.  2312.  7460. 33045.  2190.  7650.
 14650. 11560.  6600. 10970. 16140. 11890.  6210.  8390.  5230.  2800.
  6960.  4560.  5430. 10050.  6230.  8470.  8800. 29190. 10580. 13810.
 12140. 13260.  7680.  8250.  7210.  8780. 12260.  6180.  4590. 19070.
  8150. 16520.  9050. 14200.  7890. 13110. 11480. 16600.  5480.  7760.
 18100. 13360.  5500. 10000.  9470.  5330.  9770.  9810.  2050. 15110.
  9260.  6360.  8840. 11470. 18540. 11570. 10010.  6590.  6980.  8490.
  7860.  5650.  7690.  5090.  4050.  7980. 12560.  7950.  6250.  5460.
 18520.  8370.  6940.  7140. 13140. 12240. 10380. 14470. 15520.  8530.
  5970.  8160. 10640. 10400.  8930. 10040. 14210. 13680. 10670. 12510.
  5160. 10420. 13370.  8880. 15700. 16230.  7870.  4400. 10220. 13670.
 16090.  6670.  7050. 11770.  9430.  4270.  8050.  5640.  7120.  9610.
  9350.  6470. 11020.  3780. 16590.  5290.  8260.  9220.  6440. 17390.
  3890. 11070. 11690.  9690.  5610. 10830. 12110. 12400.  7310. 11190.
  7770. 11900.  9530. 13080. 11830. 11410.  9620.  7100.  9630. 12780.
  9960.  9270.  6150.  6830.  5510.  7540. 15770. 15040.  6012. 12420.
 10840. 12620. 13790. 15390.  5140. 12540.  7560.  5600.  8600. 10500.
 10160.  6110.  9230.  8180.  8240.  8480.  8650. 10320. 13500.  3870.
 15650. 10070. 16360.  9000.  7070.  6330.  8610.  9720. 12310. 18720.
 10920. 14020. 14580. 14620.  5250.  4720. 12870. 12520. 15590.  6660.
 10680. 10980. 14640. 13030.  1050. 21190. 12790.  7790.  9860. 22180.
 25710.  8230. 20090.  4340. 11330. 11640. 23580. 12230. 11240. 26660.
 10430.  4800.  5730. 10001. 14110. 14530.  8100. 11800. 11280.  5570.
 12000. 10450. 13200. 15000.  4100. 20000. 10600. 13780.  9020. 10120.
 12070. 11490. 16810.  4350. 11400.  5661.  8850.  4970.  8690. 25000.
 10780. 11130.  9090. 11110.  6040. 13620. 11350. 28050.  9130. 10460.
  8590. 11970. 20970.  4900.  4920.  8190.  6060. 10280.  9730. 13700.
  5110. 10190.  6090. 15570. 12990.  6760.  9290.  3680.  7700.  6910.
  9390.  1541. 10060.  5117. 12270. 19960. 11220. 11060.  4600. 15920.
  9360. 11820. 11620.  9250. 13650. 15080. 10730.  8320.  3960.  7410.
  3700. 15290. 15320. 14250. 10170.  6030.  4170. 12550. 12610. 14070.
 11710. 19510.  7420. 19970. 12190. 16800.  8900.  8710.  5180. 13350.
  8620. 15020. 12670. 11360. 18880. 13240.  8350. 11840. 13270.  9600.
 14140.  5920.  9440.  8670.  3440.  8890.  3560. 15750. 11450.  9550.
 15600.]
BB: [ 1.  0. nan]
INOTROPICOS: [ 0.  1. nan]
FUNCION VENTRICULAR IZQ: [ 1.  2.  3. nan  4.]
IAM HOSP(SI INTERNO POR ANGINA) O REIAM: [0 1 '1' nan]

Luego de limpiar los valores no deseados, pasamos todas las columnas a float (tipo de dato numérico que admite NaN) asi podemos empezar la imputación de los valores faltantes.

In [8]:
# Convertir las columnas a float para admitir NaN
df[object_columns] = df[object_columns].apply(pd.to_numeric, errors='coerce')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1818 entries, 0 to 1817
Data columns (total 74 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   EDAD                                     1818 non-null   int64
 1   SEX0                                     1818 non-null   int64
 2   HTA                                      1818 non-null   int64
 3   DBT                                      1818 non-null   int64
 4   DLP                                      1818 non-null   int64
 5   TABAQ                                    1818 non-null   int64
 6   ANTEC IAM / Angina inestable             1818 non-null   int64
 7   ANTEC BY PASS                            1818 non-null   int64
 8   ANTEC ATC                                1818 non-null   int64
 9   ANTEC ACE                                1818 non-null   int64
 10  ANTEC INS RENAL                          1818 non-null   int64
 11  ACV TIA PREV                             1818 non-null   int64
 12  EPOC                                     1818 non-null   int64
 13  CLAUD ITTE                               1818 non-null   int64
 14  BB PREV                                  1818 non-null   int64
 15   IECA/AT2  PREV                          1818 non-null   int64
 16  B CA PREV                                1818 non-null   int64
 17  AAS PREV                                 1818 non-null   int64
 18  HIPOGLUCEMIANTES                         1818 non-null   int64
 19  DIURETICOS                               1818 non-null   int64
 20  INSULINA                                 1818 non-null   int64
 21  PESO Kg                                  1725 non-null   float64
 22  ALTURA cm                                1698 non-null   float64
 23  ECG INFRA ST                             1818 non-null   int64
 24  ECG SUPRA ST                             1818 non-null   int64
 25  ECG INV T                                1818 non-null   int64
 26  BRI                                      1817 non-null   float64
 27  BRD                                      1818 non-null   int64
 28  ECG MCP                                  1818 non-null   int64
 29  ECG FA                                   1817 non-null   float64
 30  tropst                                   1816 non-null   float64
 31  TnT Ultrasensible                        1818 non-null   int64
 32  TROPONINA MAX                            1809 non-null   float64
 33  Elevacion troponina T                    1818 non-null   int64
 34  CREAT                                    1808 non-null   float64
 35  GLUCEMIA INGR                            1735 non-null   float64
 36  GB                                       1752 non-null   float64
 37  TAS INGRESO                              1806 non-null   float64
 38  FC INGRESO                               1807 non-null   float64
 39  KILLIP Ingreso                           1818 non-null   int64
 40  AAS                                      1818 non-null   int64
 41  BB                                       1800 non-null   float64
 42  IECA                                     1818 non-null   int64
 43  AT2                                      1817 non-null   float64
 44  Clopi - prasu - tica                     1818 non-null   int64
 45  HEP sc o iv                              1818 non-null   int64
 46  IIb IIIa                                 1818 non-null   int64
 47  B CA                                     1817 non-null   float64
 48  ESTATINAS                                1818 non-null   int64
 49  HIPOGLUC METFORM                         1817 non-null   float64
 50  HIPOGL SULFAN                            1818 non-null   int64
 51  HIPOGL GLITAZ                            1814 non-null   float64
 52  INSULINA.1                               1817 non-null   float64
 53  INS + HIPOGL                             1817 non-null   float64
 54  INOTROPICOS                              1800 non-null   float64
 55  FUNCION VENTRICULAR IZQ                  1810 non-null   float64
 56  DIAGNOSTICO                              1817 non-null   float64
 57  PRUEBA FUNC.                             1818 non-null   int64
 58  PRUEBA FUNC DE ALTO RIESGO               1817 non-null   float64
 59  CCG                                      1818 non-null   int64
 60  TRONCO                                   1817 non-null   float64
 61  NUMERO VASOS                             1816 non-null   float64
 62  ATC PRIMARIA                             1818 non-null   int64
 63  ATC INTRAHOSP                            1818 non-null   int64
 64  TROMBOL                                  1817 non-null   float64
 65  CRM                                      1815 non-null   float64
 66  MUERTE HOSP                              1818 non-null   int64
 67  IAM HOSP(SI INTERNO POR ANGINA) O REIAM  1815 non-null   float64
 68  APIAM                                    1815 non-null   float64
 69  Peor KILLIP                              1818 non-null   int64
 70  ANGINA REFRACT o RECURR                  1815 non-null   float64
 71   ACV/TIA                                 1814 non-null   float64
 72  SANGRADO MAYOR*                          1814 non-null   float64
 73  I RENAL AGUDA                            1816 non-null   float64
dtypes: float64(32), int64(42)
memory usage: 1.0 MB

In [10]:
print_column_with_nan(df, 2)

PESO Kg NaNs: 93 - 5.115511551155116%
ALTURA cm NaNs: 120 - 6.600660066006601%
GLUCEMIA INGR NaNs: 83 - 4.565456545654565%
GB NaNs: 66 - 3.6303630363036303%

La imputación de los datos la vamos a hacer en dos partes. Para aquellas features que tienen valores faltantes mayores o iguales al 2% del total, imputamos mediante la técnica MICE (Multiple Imputation by Chained Equations). Para las features con valores faltantes menores a 2%, hacemos una imputación aleatoria ya que no afecta la distribución de la feature en particular.

In [11]:
# Lista de columnas para imputar mediante MICE
mice_imputation_columns = ['PESO Kg', 'ALTURA cm', 'GLUCEMIA INGR', 'GB']

### Imputacion Univariada - Imputación por muestreo aleatorio

In [12]:
# Creamos una copia del dataframe
df_copy = df.copy()

In [16]:
nan_columns = get_columns_with_nan(df_copy)

In [20]:
# Obtenemos las columnas que contienen NaN menor a 2%
random_imputation_columns = [col for col in nan_columns if col not in mice_imputation_columns]

In [22]:
for column in random_imputation_columns:
    # Obtenemos los valores no NaN de la columna
    no_nan_values = df_copy[column].dropna()
    # Imputamos los valores NaN con muestreo aleatorio de los valores no NaN
    df_copy[column] = df_copy[column].apply(
        lambda x: np.random.choice(no_nan_values) if np.isnan(x) else x
    )

In [24]:
print_column_with_nan(df_copy)

EDAD NaNs: 0 - 0.0%
SEX0 NaNs: 0 - 0.0%
HTA NaNs: 0 - 0.0%
DBT NaNs: 0 - 0.0%
DLP NaNs: 0 - 0.0%
TABAQ NaNs: 0 - 0.0%
ANTEC IAM / Angina inestable NaNs: 0 - 0.0%
ANTEC BY PASS NaNs: 0 - 0.0%
ANTEC ATC NaNs: 0 - 0.0%
ANTEC ACE NaNs: 0 - 0.0%
ANTEC INS RENAL NaNs: 0 - 0.0%
ACV TIA PREV NaNs: 0 - 0.0%
EPOC NaNs: 0 - 0.0%
CLAUD ITTE NaNs: 0 - 0.0%
BB PREV NaNs: 0 - 0.0%
 IECA/AT2  PREV NaNs: 0 - 0.0%
B CA PREV NaNs: 0 - 0.0%
AAS PREV NaNs: 0 - 0.0%
HIPOGLUCEMIANTES NaNs: 0 - 0.0%
DIURETICOS NaNs: 0 - 0.0%
INSULINA NaNs: 0 - 0.0%
PESO Kg NaNs: 93 - 5.115511551155116%
ALTURA cm NaNs: 120 - 6.600660066006601%
ECG INFRA ST NaNs: 0 - 0.0%
ECG SUPRA ST NaNs: 0 - 0.0%
ECG INV T NaNs: 0 - 0.0%
BRI NaNs: 0 - 0.0%
BRD NaNs: 0 - 0.0%
ECG MCP NaNs: 0 - 0.0%
ECG FA NaNs: 0 - 0.0%
tropst NaNs: 0 - 0.0%
TnT Ultrasensible NaNs: 0 - 0.0%
TROPONINA MAX NaNs: 0 - 0.0%
Elevacion troponina T NaNs: 0 - 0.0%
CREAT NaNs: 0 - 0.0%
GLUCEMIA INGR NaNs: 83 - 4.565456545654565%
GB NaNs: 66 - 3.6303630363036303%
TAS INGRESO NaNs: 0 - 0.0%
FC INGRESO NaNs: 0 - 0.0%
KILLIP Ingreso NaNs: 0 - 0.0%
AAS NaNs: 0 - 0.0%
BB NaNs: 0 - 0.0%
IECA NaNs: 0 - 0.0%
AT2 NaNs: 0 - 0.0%
Clopi - prasu - tica NaNs: 0 - 0.0%
HEP sc o iv NaNs: 0 - 0.0%
IIb IIIa NaNs: 0 - 0.0%
B CA NaNs: 0 - 0.0%
ESTATINAS NaNs: 0 - 0.0%
HIPOGLUC METFORM NaNs: 0 - 0.0%
HIPOGL SULFAN NaNs: 0 - 0.0%
HIPOGL GLITAZ NaNs: 0 - 0.0%
INSULINA.1 NaNs: 0 - 0.0%
INS + HIPOGL NaNs: 0 - 0.0%
INOTROPICOS NaNs: 0 - 0.0%
FUNCION VENTRICULAR IZQ NaNs: 0 - 0.0%
DIAGNOSTICO NaNs: 0 - 0.0%
PRUEBA FUNC. NaNs: 0 - 0.0%
PRUEBA FUNC DE ALTO RIESGO NaNs: 0 - 0.0%
CCG NaNs: 0 - 0.0%
TRONCO NaNs: 0 - 0.0%
NUMERO VASOS NaNs: 0 - 0.0%
ATC PRIMARIA NaNs: 0 - 0.0%
ATC INTRAHOSP NaNs: 0 - 0.0%
TROMBOL NaNs: 0 - 0.0%
CRM NaNs: 0 - 0.0%
MUERTE HOSP NaNs: 0 - 0.0%
IAM HOSP(SI INTERNO POR ANGINA) O REIAM NaNs: 0 - 0.0%
APIAM NaNs: 0 - 0.0%
Peor KILLIP NaNs: 0 - 0.0%
ANGINA REFRACT o RECURR NaNs: 0 - 0.0%
 ACV/TIA NaNs: 0 - 0.0%
SANGRADO MAYOR* NaNs: 0 - 0.0%
I RENAL AGUDA NaNs: 0 - 0.0%

### MICE (Multiple Imputation by Chained Equations)

- Calcula valores faltantes para cada columna como una regresión lineal de las restantes (si bien también se pueden usar otros modelos). Como utiliza el resto de las columnas, es un método **multivariado**.
- Es iterativo porque repite este proceso hasta que la diferencia entre las dos últimas iteraciones sea cercana a cero.

Búsqueda de mejores parámetros por Grid Search.

In [25]:
X = df_copy.drop([TARGET], axis=1)
y = df_copy[TARGET]

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.model_selection import GridSearchCV, RepeatedStratifiedKFold
from sklearn.impute import IterativeImputer

# Definir el pipeline con imputación iterativa y regresión logística
pipeline = Pipeline(steps=[
    ('imputer', IterativeImputer(max_iter=10, random_state=0)),
    ('lr', LogisticRegression(max_iter=1000))
])

# Definir los parámetros para la búsqueda en cuadrícula
param_grid = {
    "imputer__n_nearest_features": [None] + list(range(1, X.shape[1] + 1))
}

# Configurar la validación cruzada repetida
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=5, random_state=42)

# Configurar la búsqueda en cuadrícula
grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=cv, scoring="f1", n_jobs=-1)

# Ajustar el modelo a los datos de entrenamiento
grid_search.fit(X, y)

# Imprimir los mejores parámetros y el mejor puntaje F1
print("Mejores parámetros encontrados:")
print(grid_search.best_params_)
print("\nMejor puntaje F1:")
print(grid_search.best_score_)

c:\Users\andre\workspace\HA-mortality-prediction\venv\Lib\site-packages\sklearn\impute\_iterative.py:801: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

Mejores parámetros encontrados:
{'imputer__n_nearest_features': 28}

Mejor puntaje F1:
0.4465724528085546

c:\Users\andre\workspace\HA-mortality-prediction\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [28]:
best_mice_imputer = grid_search.best_estimator_['imputer']

# Imputar solo las columnas de mice_imputation_columns
X_imputed = best_mice_imputer.transform(X)
df_imputed = df_copy.copy()
df_imputed[mice_imputation_columns] = X_imputed[:, [df_copy.columns.get_loc(col) for col in mice_imputation_columns]]

In [29]:
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1818 entries, 0 to 1817
Data columns (total 74 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   EDAD                                     1818 non-null   int64
 1   SEX0                                     1818 non-null   int64
 2   HTA                                      1818 non-null   int64
 3   DBT                                      1818 non-null   int64
 4   DLP                                      1818 non-null   int64
 5   TABAQ                                    1818 non-null   int64
 6   ANTEC IAM / Angina inestable             1818 non-null   int64
 7   ANTEC BY PASS                            1818 non-null   int64
 8   ANTEC ATC                                1818 non-null   int64
 9   ANTEC ACE                                1818 non-null   int64
 10  ANTEC INS RENAL                          1818 non-null   int64
 11  ACV TIA PREV                             1818 non-null   int64
 12  EPOC                                     1818 non-null   int64
 13  CLAUD ITTE                               1818 non-null   int64
 14  BB PREV                                  1818 non-null   int64
 15   IECA/AT2  PREV                          1818 non-null   int64
 16  B CA PREV                                1818 non-null   int64
 17  AAS PREV                                 1818 non-null   int64
 18  HIPOGLUCEMIANTES                         1818 non-null   int64
 19  DIURETICOS                               1818 non-null   int64
 20  INSULINA                                 1818 non-null   int64
 21  PESO Kg                                  1818 non-null   float64
 22  ALTURA cm                                1818 non-null   float64
 23  ECG INFRA ST                             1818 non-null   int64
 24  ECG SUPRA ST                             1818 non-null   int64
 25  ECG INV T                                1818 non-null   int64
 26  BRI                                      1818 non-null   float64
 27  BRD                                      1818 non-null   int64
 28  ECG MCP                                  1818 non-null   int64
 29  ECG FA                                   1818 non-null   float64
 30  tropst                                   1818 non-null   float64
 31  TnT Ultrasensible                        1818 non-null   int64
 32  TROPONINA MAX                            1818 non-null   float64
 33  Elevacion troponina T                    1818 non-null   int64
 34  CREAT                                    1818 non-null   float64
 35  GLUCEMIA INGR                            1818 non-null   float64
 36  GB                                       1818 non-null   float64
 37  TAS INGRESO                              1818 non-null   float64
 38  FC INGRESO                               1818 non-null   float64
 39  KILLIP Ingreso                           1818 non-null   int64
 40  AAS                                      1818 non-null   int64
 41  BB                                       1818 non-null   float64
 42  IECA                                     1818 non-null   int64
 43  AT2                                      1818 non-null   float64
 44  Clopi - prasu - tica                     1818 non-null   int64
 45  HEP sc o iv                              1818 non-null   int64
 46  IIb IIIa                                 1818 non-null   int64
 47  B CA                                     1818 non-null   float64
 48  ESTATINAS                                1818 non-null   int64
 49  HIPOGLUC METFORM                         1818 non-null   float64
 50  HIPOGL SULFAN                            1818 non-null   int64
 51  HIPOGL GLITAZ                            1818 non-null   float64
 52  INSULINA.1                               1818 non-null   float64
 53  INS + HIPOGL                             1818 non-null   float64
 54  INOTROPICOS                              1818 non-null   float64
 55  FUNCION VENTRICULAR IZQ                  1818 non-null   float64
 56  DIAGNOSTICO                              1818 non-null   float64
 57  PRUEBA FUNC.                             1818 non-null   int64
 58  PRUEBA FUNC DE ALTO RIESGO               1818 non-null   float64
 59  CCG                                      1818 non-null   int64
 60  TRONCO                                   1818 non-null   float64
 61  NUMERO VASOS                             1818 non-null   float64
 62  ATC PRIMARIA                             1818 non-null   int64
 63  ATC INTRAHOSP                            1818 non-null   int64
 64  TROMBOL                                  1818 non-null   float64
 65  CRM                                      1818 non-null   float64
 66  MUERTE HOSP                              1818 non-null   int64
 67  IAM HOSP(SI INTERNO POR ANGINA) O REIAM  1818 non-null   float64
 68  APIAM                                    1818 non-null   float64
 69  Peor KILLIP                              1818 non-null   int64
 70  ANGINA REFRACT o RECURR                  1818 non-null   float64
 71   ACV/TIA                                 1818 non-null   float64
 72  SANGRADO MAYOR*                          1818 non-null   float64
 73  I RENAL AGUDA                            1818 non-null   float64
dtypes: float64(32), int64(42)
memory usage: 1.0 MB

Volvemos las columnnas que eran object a sus tipos originales:

In [31]:
df_imputed[object_columns]

,ALTURA cm,TROPONINA MAX,CREAT,GLUCEMIA INGR,GB,BB,INOTROPICOS,FUNCION VENTRICULAR IZQ,IAM HOSP(SI INTERNO POR ANGINA) O REIAM
0,155.0,0.20,0.58,160.0,8920.000000,1.0,0.0,1.0,0.0
1,165.0,0.05,1.06,131.0,10340.000000,1.0,0.0,2.0,0.0
2,172.0,0.00,0.83,98.0,6780.000000,1.0,0.0,1.0,0.0
3,162.0,0.00,1.06,106.0,5830.000000,1.0,0.0,1.0,0.0
4,175.0,0.00,0.85,110.0,14990.000000,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
1813,180.0,45.00,1.00,126.0,8334.973778,1.0,0.0,1.0,0.0
1814,182.0,45.00,0.40,115.0,9655.860734,1.0,0.0,1.0,0.0
1815,178.0,132.00,0.95,124.0,9044.460349,1.0,0.0,2.0,0.0
1816,170.0,103.00,0.80,113.0,9550.000000,1.0,0.0,1.0,0.0
1817,165.0,3670.00,0.90,111.0,15600.000000,1.0,0.0,1.0,0.0

In [32]:
df_imputed['ALTURA cm'] = df_imputed['ALTURA cm'].astype(int)
df_imputed['GLUCEMIA INGR'] = df_imputed['GLUCEMIA INGR'].astype(int)
df_imputed['GB'] = df_imputed['GB'].astype(int)
df_imputed['BB'] = df_imputed['BB'].astype(int)
df_imputed['INOTROPICOS'] = df_imputed['INOTROPICOS'].astype(int)
df_imputed['FUNCION VENTRICULAR IZQ'] = df_imputed['FUNCION VENTRICULAR IZQ'].astype(int)
df_imputed['IAM HOSP(SI INTERNO POR ANGINA) O REIAM'] = df_imputed['IAM HOSP(SI INTERNO POR ANGINA) O REIAM'].astype(int)

df_imputed['TROPONINA MAX'] = df_imputed['TROPONINA MAX'].astype(float)
df_imputed['CREAT'] = df_imputed['CREAT'].astype(float)

In [33]:
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1818 entries, 0 to 1817
Data columns (total 74 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   EDAD                                     1818 non-null   int64
 1   SEX0                                     1818 non-null   int64
 2   HTA                                      1818 non-null   int64
 3   DBT                                      1818 non-null   int64
 4   DLP                                      1818 non-null   int64
 5   TABAQ                                    1818 non-null   int64
 6   ANTEC IAM / Angina inestable             1818 non-null   int64
 7   ANTEC BY PASS                            1818 non-null   int64
 8   ANTEC ATC                                1818 non-null   int64
 9   ANTEC ACE                                1818 non-null   int64
 10  ANTEC INS RENAL                          1818 non-null   int64
 11  ACV TIA PREV                             1818 non-null   int64
 12  EPOC                                     1818 non-null   int64
 13  CLAUD ITTE                               1818 non-null   int64
 14  BB PREV                                  1818 non-null   int64
 15   IECA/AT2  PREV                          1818 non-null   int64
 16  B CA PREV                                1818 non-null   int64
 17  AAS PREV                                 1818 non-null   int64
 18  HIPOGLUCEMIANTES                         1818 non-null   int64
 19  DIURETICOS                               1818 non-null   int64
 20  INSULINA                                 1818 non-null   int64
 21  PESO Kg                                  1818 non-null   float64
 22  ALTURA cm                                1818 non-null   int32
 23  ECG INFRA ST                             1818 non-null   int64
 24  ECG SUPRA ST                             1818 non-null   int64
 25  ECG INV T                                1818 non-null   int64
 26  BRI                                      1818 non-null   float64
 27  BRD                                      1818 non-null   int64
 28  ECG MCP                                  1818 non-null   int64
 29  ECG FA                                   1818 non-null   float64
 30  tropst                                   1818 non-null   float64
 31  TnT Ultrasensible                        1818 non-null   int64
 32  TROPONINA MAX                            1818 non-null   float64
 33  Elevacion troponina T                    1818 non-null   int64
 34  CREAT                                    1818 non-null   float64
 35  GLUCEMIA INGR                            1818 non-null   int32
 36  GB                                       1818 non-null   int32
 37  TAS INGRESO                              1818 non-null   float64
 38  FC INGRESO                               1818 non-null   float64
 39  KILLIP Ingreso                           1818 non-null   int64
 40  AAS                                      1818 non-null   int64
 41  BB                                       1818 non-null   int32
 42  IECA                                     1818 non-null   int64
 43  AT2                                      1818 non-null   float64
 44  Clopi - prasu - tica                     1818 non-null   int64
 45  HEP sc o iv                              1818 non-null   int64
 46  IIb IIIa                                 1818 non-null   int64
 47  B CA                                     1818 non-null   float64
 48  ESTATINAS                                1818 non-null   int64
 49  HIPOGLUC METFORM                         1818 non-null   float64
 50  HIPOGL SULFAN                            1818 non-null   int64
 51  HIPOGL GLITAZ                            1818 non-null   float64
 52  INSULINA.1                               1818 non-null   float64
 53  INS + HIPOGL                             1818 non-null   float64
 54  INOTROPICOS                              1818 non-null   int32
 55  FUNCION VENTRICULAR IZQ                  1818 non-null   int32
 56  DIAGNOSTICO                              1818 non-null   float64
 57  PRUEBA FUNC.                             1818 non-null   int64
 58  PRUEBA FUNC DE ALTO RIESGO               1818 non-null   float64
 59  CCG                                      1818 non-null   int64
 60  TRONCO                                   1818 non-null   float64
 61  NUMERO VASOS                             1818 non-null   float64
 62  ATC PRIMARIA                             1818 non-null   int64
 63  ATC INTRAHOSP                            1818 non-null   int64
 64  TROMBOL                                  1818 non-null   float64
 65  CRM                                      1818 non-null   float64
 66  MUERTE HOSP                              1818 non-null   int64
 67  IAM HOSP(SI INTERNO POR ANGINA) O REIAM  1818 non-null   int32
 68  APIAM                                    1818 non-null   float64
 69  Peor KILLIP                              1818 non-null   int64
 70  ANGINA REFRACT o RECURR                  1818 non-null   float64
 71   ACV/TIA                                 1818 non-null   float64
 72  SANGRADO MAYOR*                          1818 non-null   float64
 73  I RENAL AGUDA                            1818 non-null   float64
dtypes: float64(25), int32(7), int64(42)
memory usage: 1001.4 KB

In [34]:
df_imputed.to_csv('../data/imputed_data.csv')